### ISSUE TITLE
fine-3:/evm.log showing [fog][WARNING] Unrecognized arguments: google_client_options

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-providers-google#12]
Hi 

We have a fine-3 miq instance with google providers  added and it is showing lots of warning message on "google_client_options"

* miq info from ap command

```
<snipped>
ManageIQ Version:        fine-3
<snipped>
```
* lots of warning message like this
```
[root@miq01 log]# grep google_client_options evm.log |wc
   4337   17348  264557
[root@miq01 log]# wc evm.log
  23960  174790 2601624 evm.log
[root@miq01 log]#

```
* References:
   * http://talk.manageiq.org/t/unrecognized-arguments-google-client-options/2607

**Comment by agrare** [comment]
@selmanj this looks like it is coming from `fog-core` in [`Fog::Service#validate_options`](https://github.com/fog/fog-core/blob/master/lib/fog/core/service.rb#L250)
We pass `:google_client_options` here https://github.com/ManageIQ/manageiq-providers-google/blob/master/app/models/manageiq/providers/google/manager_mixin.rb#L38-L52 is there something we should be doing differently?

**Comment by juliancheal** [comment]
@agrare Yes, `: google_client_options` is used to pass proxy details to the google client gem via `fog-google` see this PR https://github.com/fog/fog-google/pull/154#issuecomment-249173429

So looks like this is a bug in `fog`. I'll take a look.

**Comment by juliancheal** [comment]
@miq-bot assign juliancheal

**Comment by agrare** [comment]
Thanks @juliancheal !!

**Comment by juliancheal** [comment]
So this was actually fixed in `fog-google` https://github.com/fog/fog-google/pull/198 and is in the `0.5.4` release https://github.com/fog/fog-google/blob/v0.5.4/lib/fog/compute/google.rb.

So not sure why we're still getting it.

**Comment by juliancheal** [comment]
This has been fixed in master https://github.com/ManageIQ/manageiq-providers-google/blob/master/manageiq-providers-google.gemspec#L16 and will be available in the `G` release.

**Comment by blomquisg** [comment]
Closing based on [@juliancheal's comment](https://github.com/ManageIQ/manageiq-providers-google/issues/12#issuecomment-333874468).
