### ISSUE TITLE
GCE default cloud network not discovered

### ISSUE THREAD

**Issue by bsogithub** [ManageIQ/manageiq-providers-google#130]
For Google Cloud Engine, each new project starts with a default network. The default network is an auto mode VPC network with pre-populated firewall rules.

There is a default VPC network on GCE:
![image](https://user-images.githubusercontent.com/29459925/81568540-e91d0b80-936b-11ea-9adf-951a0ff29bc9.png)

But manageiq could not find it:
![image](https://user-images.githubusercontent.com/29459925/81568723-300b0100-936c-11ea-8c82-d81c45c03cbe.png)

As a result, you will not be able to provision instance:
![image.png](https://zenhub.ibm.com/images/5a5cbc4260749ee5120845ad/5175f647-d686-4f0c-81d1-0f05192f5a83)
Because "'Environment/Cloud Network' is required"

**Comment by chessbyte** [comment]
@agrare does https://github.com/ManageIQ/manageiq-providers-google/pull/131 address this issue?

**Comment by agrare** [comment]
@chessbyte yes the error in https://github.com/ManageIQ/manageiq-providers-google/pull/131 was preventing the NetworkManager refresh from finishing, thus no inventory under the NetworkManager (including CloudNetworks) were being saved at all.
