### ISSUE TITLE
[WIP] Replace `fog-google` with native calls to `google-api-ruby-client`

### ISSUE THREAD

**Issue by juliancheal** [ManageIQ/manageiq-providers-google#15]

**Comment by juliancheal** [comment]
@miq-bot assign juliancheal

**Comment by juliancheal** [comment]
This is just a spike.

**Comment by bronaghs** [comment]
hey @juliancheal  - I don't follow. Can you provide some details on this?

**Comment by juliancheal** [comment]
@bronaghs was a conversation with Adam and Ladas at the summit. Might be moot now…

**Comment by agrare** [comment]
@juliancheal I don't think it is moot, we don't need the abstraction that fog provides and talking with @selmanj he recommends https://github.com/GoogleCloudPlatform/google-cloud-ruby would let us stay up to date faster without needing to wait for something to get added to fog-google.

The only downside right now is that there is no `Compute` support yet, so maybe `google-api-client` is a good intermediate step.  Worth investigating especially if it will make going to `google-cloud-ruby` easier.
