### ISSUE TITLE
Upgrade to fog-google version 0.6.0

### ISSUE THREAD

**Issue by bronaghs** [ManageIQ/manageiq-providers-google#17]
Upgrade the manageiq-providers-google to version ~~0.6.0~~ 1.0 of the fog-google gem. 
This will expose incompatibilities [here](https://github.com/ManageIQ/manageiq-providers-google/blob/master/app/models/manageiq/providers/google/cloud_manager/metrics_capture.rb#L138) and where we read the metric data returned in the response.

Helpful links:
       https://cloud.google.com/monitoring/api/v3/migration#start-migration
       https://cloud.google.com/monitoring/api/v3/migration#timeserieslist

Update - 3/9/18 - the fog-google-gem v1.0 has been released so we should upgrade to that. The above links may still be helpful, but I understand other areas of the provider will likely break as well.

**Comment by tumido** [comment]
@bronaghs, I'd like to be assigned to this ticket instead of @juliancheal - based on the discussion I have with both of you. In the process of implementing this, I hope in solving the [bug 1511099](https://bugzilla.redhat.com/show_bug.cgi?id=1511099) as well.

**Comment by bronaghs** [comment]
@miq-bot assign @tumido

**Comment by tumido** [comment]
@miq-bot remove_label stale
@miq-bot close_issue

This issue is resolved via #54, #59, #64

**Comment by tumido** [comment]
@miq-bot assign tumido
