### ISSUE TITLE
Requested entity was not found when adding the provider

### ISSUE THREAD

**Issue by handersonhp** [ManageIQ/manageiq-providers-google#242]
Good morning, I'm having trouble adding Google to the ManageIQ provider, and all the tutorials I'm looking for, I can't do it anyway.
Follow error logs.
--- Credential validation was not successful: Requested entity was not found.

**Comment by Fryguy** [comment]
@agrare Can you take a look at this one?  If it's a valid issue, please transfer to manageiq-providers-google.
