### ISSUE TITLE
Google inventory parser may not set cloud volume type

### ISSUE THREAD

**Issue by blomquisg** [ManageIQ/manageiq-providers-google#26]
Looking at [the code](https://github.com/ManageIQ/manageiq-providers-google/blob/a3d7df99184446bf86f0f72d3e3f3c7e5275912b/app/models/manageiq/providers/google/cloud_manager/refresh_parser.rb#L125), it looks like the `CloudManager::RefreshParser` is not setting the `type` in `parse_volumes`.

The other thing to point out is that Google doesn't have a `CloudManager::CloudVolume` class, so it's possible that not setting the `type` is fine.

I think it's probably better to:

1. Specifically subclass `::CloudVolume` to `::ManageIQ::Providers::Google::CloudManager::CloudVolume`, and 
2. Update the `refresh_parser` to set the `type` to this new class.

/cc @Fryguy thoughts on this?

**Comment by djberg96** [comment]
@juliancheal I don't suppose you happen to know what volume operations google supports?

**Comment by JPrause** [comment]
Appears to still be active, removing stale label.
@miq-bot remove_label stale

**Comment by bronaghs** [comment]
This is not a priority, closing
