### ISSUE TITLE
Travis failing with bad authentication option

### ISSUE THREAD

**Issue by AlexanderZagaynov** [ManageIQ/manageiq-providers-google#94]
Recently Travis started [failing](https://travis-ci.org/ManageIQ/manageiq-providers-google/jobs/511824099) with google auth error and unknown VCR request.
I found suspicious change in the `fog-google` gem: https://github.com/fog/fog-google/pull/442 but probably it's only reveals bug in our own code.
There was also [slight changes](https://github.com/ManageIQ/manageiq-providers-google/pull/91) in our code recently, which also touches involved code files, but most probably they're unrelated.

I'm running test with `bundle exec rspec spec/models/manageiq/providers/google/cloud_manager/refresher_spec.rb:57` command ([code](https://github.com/ManageIQ/manageiq-providers-google/blob/06efe2ab0a4a58d09c03518aae8ca57412c439a8/spec/models/manageiq/providers/google/cloud_manager/refresher_spec.rb#L57)).

What I see, is that on the second iteration we has 2 authentication records (first is our predefined, second - gathered with refresh).
![auth1](https://user-images.githubusercontent.com/7778414/55540440-46538180-56c3-11e9-8600-45b5332cb42c.png)
![auth2](https://user-images.githubusercontent.com/7778414/55540447-4b183580-56c3-11e9-9ec2-de0ca628190a.png)

Predefined record has `authtype` attribute with value `default`.
That attribute is `nil` in the second (gathered) record.

As we're not passing `auth_type` option [here](https://github.com/ManageIQ/manageiq-providers-google/blob/06efe2ab0a4a58d09c03518aae8ca57412c439a8/app/models/manageiq/providers/google/manager_mixin.rb#L14), system tries to find [default](https://github.com/ManageIQ/manageiq/blob/629474ca44471d34b19f0ec4682eaece5f79394e/app/models/mixins/authentication_mixin.rb#L424) [one](https://github.com/ManageIQ/manageiq/blob/629474ca44471d34b19f0ec4682eaece5f79394e/app/models/mixins/authentication_mixin.rb#L57).

Problem is that even if second record has `nil` in its `authtype` field, system [compares](https://github.com/ManageIQ/manageiq/blob/629474ca44471d34b19f0ec4682eaece5f79394e/app/models/mixins/authentication_mixin.rb#L221) not it, but additional method's [result](https://github.com/ManageIQ/manageiq/blob/629474ca44471d34b19f0ec4682eaece5f79394e/app/models/authentication.rb#L95), which is equals to the same `default` value we have.

So it takes first found record, but it is not that record we need. As a result, google auth fails, and new gem's changes trying to find something else, which leads to unhanded VCR requests.

**Comment by AlexanderZagaynov** [comment]
It also can be because of recent PostgreSQL [version change](https://github.com/ManageIQ/manageiq/pull/18547) - if new version returns results ordered in a different way (when they're unsorted).

**Comment by AlexanderZagaynov** [comment]
One possible way I see, is to change [here](https://github.com/ManageIQ/manageiq/blob/629474ca44471d34b19f0ec4682eaece5f79394e/app/models/mixins/authentication_mixin.rb#L220) call for [`available_authentications`](https://github.com/ManageIQ/manageiq/blob/629474ca44471d34b19f0ec4682eaece5f79394e/app/models/mixins/authentication_mixin.rb#L435) to call for [`authentication_for_providers`](https://github.com/ManageIQ/manageiq/blob/629474ca44471d34b19f0ec4682eaece5f79394e/app/models/mixins/authentication_mixin.rb#L73), at least override it in the Google's [`CloudManager`](https://github.com/ManageIQ/manageiq-providers-google/blob/06efe2ab0a4a58d09c03518aae8ca57412c439a8/app/models/manageiq/providers/google/cloud_manager.rb) and [`NetworkManager`](https://github.com/ManageIQ/manageiq-providers-google/blob/06efe2ab0a4a58d09c03518aae8ca57412c439a8/app/models/manageiq/providers/google/network_manager.rb) subclasses.

**Comment by AlexanderZagaynov** [comment]
@agrare @tumido any thoughts?

**Comment by agrare** [comment]
Ahh I bet it was this change https://github.com/ManageIQ/manageiq/pull/18309/files#diff-f9cace1fe4fdcec66f962b23f2110fd6L70 causing other AuthPrivateKeys to be eligible

**Comment by djberg96** [comment]
I think we can close this as of https://github.com/ManageIQ/manageiq/pull/18633. @AlexanderZagaynov or @agrare Please reopen if I'm incorrect.
